name: 'nyc_taxi_transform'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_transform:
    staging:
      +schema: nyc_taxi_bronze
      +materialized: view
    silver:
      +schema: nyc_taxi_silver
      +materialized: incremental
