version: 2

models:
  - name: gold_monthly_revenue
    description: "Reporte agregado de ingresos mensuales por proveedor."
    columns:
      - name: vendor_id
        description: "ID del proveedor."
        tests:
          - not_null
      - name: year
        description: "Año del viaje."
        tests:
          - not_null
      - name: month
        description: "Mes del viaje."
        tests:
          - not_null
      - name: total_revenue
        description: "Ingreso total (tarifas + propinas + cargos)."
        tests:
          - not_null

  - name: gold_trips_by_zone
    description: "Reporte de volumen de viajes y promedios por zona de inicio."
    columns:
      - name: pu_location_id
        description: "ID de la zona de inicio (Pickup Location)."
        tests:
          - not_null
      - name: total_trips
        description: "Número total de viajes en esa zona."
        tests:
          - not_null
